#ifndef NX_USER_H
#define NX_USER_H

// #define NX_SECURE_KEY_CLEAR 1
// #define NX_SECURE_TLS_SERVER_DISABLED 1
#define NX_SECURE_TLS_ENABLE_TLS_1_3
// #define NX_SECURE_TLS_DISABLE_SECURE_RENEGOTIATION 0
// #define NX_SECURE_TLS_DISABLE_PROTOCOL_VERSION_DOWNGRADE 1
// #define NX_SECURE_POWER_ON_SELF_TEST_MODULE_INTEGRITY_CHECK 1

#endif